/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caballos365;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;


/**
 *
 * @author alber
 */
public class pantalla extends javax.swing.JFrame {
Conexion con = new Conexion();
public static String usuarioIdentificado; // Se llenará al hacer Login
public static double saldoApp = 0.0;
public static String caballoApostado = ""; 
public static double montoApuesta = 0.0;
public static int multiplicador = 2; 

    public pantalla() {
        initComponents();
        con.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDialog5 = new javax.swing.JDialog();
        jTextField6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDialog6 = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setForeground(new java.awt.Color(0, 255, 51));
        jButton5.setText("empezar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/verdebien-ezgif.com-resize.gif"))); // NOI18N
        jDialog1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/gifmoradobien-ezgif.com-resize.gif"))); // NOI18N
        jDialog1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/AZULBIEN-ezgif.com-resize.gif"))); // NOI18N
        jDialog1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/ROJOBIEN-ezgif.com-resize.gif"))); // NOI18N
        jDialog1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/AMARILLOBIEN-ezgif.com-resize.gif"))); // NOI18N
        jDialog1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondogif.gif"))); // NOI18N
        jLabel13.setText("jLabel13");
        jDialog1.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jDialog2.setMinimumSize(new java.awt.Dimension(1920, 1080));

        jLabel3.setText("ADMIN");
        jDialog2.getContentPane().add(jLabel3, java.awt.BorderLayout.CENTER);

        jDialog3.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(74, 47, 29));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.setName("USUARIO"); // NOI18N
        jDialog3.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 590, 270, 40));

        jTextField5.setBackground(new java.awt.Color(74, 47, 29));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        jTextField5.setName("USUARIO"); // NOI18N
        jDialog3.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 270, 40));

        jTextField2.setBackground(new java.awt.Color(74, 47, 29));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setName("USUARIO"); // NOI18N
        jDialog3.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 270, 40));

        jTextField4.setBackground(new java.awt.Color(74, 47, 29));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.setName("USUARIO"); // NOI18N
        jDialog3.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, 270, 40));

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 703, 130, 30));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 500, 360, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/egitro.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jDialog3.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDialog4.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jDialog4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 630, 140));

        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 427, 630, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/MenuPrincipal1920 (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jDialog4.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 1090));

        jDialog5.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jDialog5.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jDialog5.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jDialog5.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 546, 250, 60));

        jLabel20.setText("jLabel20");
        jDialog5.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 370, -1, -1));

        jLabel21.setText("jLabel21");
        jDialog5.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 360, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Aura.jpg"))); // NOI18N
        jDialog5.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 551, -1, 50));

        jLabel19.setText("jLabel19");
        jDialog5.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/caballoamarillocap.png"))); // NOI18N
        jDialog5.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifsCaballos/SPRITES CABALLOS/caballoazulcap.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jDialog5.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 210, -1));

        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 867, 590, 130));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/ImagenInscripcionCarrera.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel12.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel12.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jDialog5.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2010, 1080));

        jDialog6.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jDialog6.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jDialog6.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jDialog6.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("0");
        jDialog6.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 780, 50));

        jButton9.setText(" ");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 570, 90));

        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 910, 830, 90));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Aura (1).jpg"))); // NOI18N
        jDialog6.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 100, 90));

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1235, 497, 590, 100));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Aura (1).jpg"))); // NOI18N
        jDialog6.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 370, 100, 90));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(204, 153, 0));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 590, 90));

        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 570, 80));
        jDialog6.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1237, 376, 580, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/MenuSaldoBueno.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jDialog6.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 720, 370, 50));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setName("CONTRASEÑA"); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 360, 40));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setName("USUARIO"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 360, 40));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 830, 190, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/IMAGEN (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 jDialog3.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    String usuario = jTextField1.getText();
//    String pass = jPasswordField1.getText();
//    
//        if (!usuario.equals("") || !pass.equals("")) {
//            try{
//                Connection conexionReal = Conexion.conectar();
//                java.sql.PreparedStatement ps = conexionReal.prepareStatement("SELECT nivel_acceso FROM usuarios WHERE (nombre = '"+usuario+"' OR email = '"+usuario+"') and contraseña = '"+pass+"'");
//                ResultSet rs=ps.executeQuery(); 
//                if (rs.next()) {
//                    String nivel_acceso=rs.getString("nivel_acceso");
//                    if (nivel_acceso.equalsIgnoreCase("Usuario")) {
//                        jDialog4.setVisible(true);
//                        pantalla obj_pantalla = new pantalla();
//        obj_pantalla.setVisible(false);
//                        
//                    }
//                    if (nivel_acceso.equalsIgnoreCase("Administrador")) {
//                        jDialog2.setVisible(true);
//                        pantalla obj_pantalla = new pantalla();
//        obj_pantalla.setVisible(false);
//                        
//                    }
//                    
//                }else{
//                    JOptionPane.showMessageDialog(null, "Usuario o Contaseña incorrectos");
//                }
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(null, "No se puede iniciar sesión");
//                
//            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Introduzca Los Datos");
//        }
    String usuarioInput = jTextField1.getText();
    String passInput = jPasswordField1.getText();
    
    if (!usuarioInput.equals("") && !passInput.equals("")) {
        try {
            Connection conexionReal = Conexion.conectar();
            
            // Consulta directa a una sola tabla
            String sql = "SELECT saldo, nombre FROM Usuarios WHERE (nombre = ? OR email = ?) AND contraseña = ?";
            
            java.sql.PreparedStatement ps = conexionReal.prepareStatement(sql);
            ps.setString(1, usuarioInput);
            ps.setString(2, usuarioInput);
            ps.setString(3, passInput);
            
            ResultSet rs = ps.executeQuery(); 
            
            if (rs.next()) {
                // Guardamos el saldo y el nombre del usuario logueado
                pantalla.saldoApp = rs.getDouble("saldo"); 
                pantalla.usuarioIdentificado = rs.getString("nombre"); 
                
                // Abrimos el menú principal
                jDialog4.setVisible(true);
                this.setVisible(false); 
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrectos");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error al iniciar sesión: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, rellena todos los campos");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    pantalla obj_pantalla = new pantalla();
        obj_pantalla.setVisible(true);   
        jDialog3.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     String nombre=jTextField2.getText();
        String edadTexto=jTextField3.getText();
        String email=jTextField5.getText();
        String contraseña=jTextField4.getText();

        if (nombre.isEmpty() || edadTexto.isEmpty() || email.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Introduce los datos");
            
                
            

        }else{
            try {
        int edad = Integer.parseInt(edadTexto);

        if (edad < 18) {
            JOptionPane.showMessageDialog(null, "Debes ser mayor de edad");
            return;
        }
            Connection conexionReal = Conexion.conectar();

            String consulta = "INSERT INTO usuarios (nombre,edad,email,contraseña)values('"+nombre+"','"+edad+"','"+email+"','"+contraseña+"')";
            try {
                java.sql.PreparedStatement ps = conexionReal.prepareStatement(consulta);
                ps.executeUpdate();
                limpiar();
            } catch (SQLException ex) {
                Logger.getLogger(pantalla.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "NO se han registrado los datos22") ;
            }catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Edad inválida");
    }

            try{
                JOptionPane.showMessageDialog(null, "Datos Guardados");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "NO se han registrado los datos") ;
            }
            
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "NO se han registrado los datos") ;
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Definimos dónde está la meta 
    int coordenadaMeta = 1800; 
    
    // 1. Reiniciamos la variable de ganador 
    
    // 2. Creamos los 5 objetos Caballo
   
    Caballo c1 = new Caballo("Rayo", jLabel5, coordenadaMeta);
    Caballo c2 = new Caballo("Pepe", jLabel6, coordenadaMeta);
    Caballo c3 = new Caballo("Joaquin", jLabel8, coordenadaMeta);
    Caballo c4 = new Caballo("Raul", jLabel7, coordenadaMeta);
    Caballo c5 = new Caballo("Raul", jLabel9, coordenadaMeta);

   
    c1.start();
    c2.start();
    c3.start();
    c4.start();
    c5.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
      
    // 4. Mostrar el nuevo diálogo
    jDialog4.setVisible(false);
    jDialog5.setVisible(true);
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jDialog5.setVisible(false);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jDialog4.setVisible(false);
        jDialog6.setVisible(true);
        jLabel14.setText(String.valueOf(pantalla.saldoApp)); // Muestra el saldo actual al abrir
        jDialog6.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    public void actualizarLabelSaldo() {
    jLabel14.setText(String.valueOf(this.saldoApp) + " Auras");
}
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      
    try {
        double monto = Double.parseDouble(jTextField7.getText());
        
        // 1. Sumamos a la variable de la app
        pantalla.saldoApp += monto;
        
        // 2. Guardar en la Base de Datos
       actualizarSaldoBD db = new actualizarSaldoBD();
        db.actualizarSaldo(pantalla.usuarioIdentificado, pantalla.saldoApp);
        
        JOptionPane.showMessageDialog(this, "Recarga de " + monto + " Auras completada.");
        jTextField7.setText(""); // Limpiamos el campo
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: Introduce un número válido.");
    }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jLabel14.setText(caballos365.pantalla.saldoApp + " Auras");
    
    
    jButton9.setEnabled(true);
    jTextField7.setText(""); // Limpiamos el cuadro de texto
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jDialog4.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Obtener la cantidad que el usuario quiere donar
        
        double montoDonado = Double.parseDouble(jTextField8.getText()); 

        // 2. Verificar si tiene saldo suficiente para donar
        if (montoDonado > pantalla.saldoApp) {
            JOptionPane.showMessageDialog(this, "No tienes suficientes Auras para realizar esta donación.");
        } else if (montoDonado <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un monto válido mayor a 0.");
        } else {
            // 3. RESTAR el monto del saldo actual
            pantalla.saldoApp -= montoDonado;

            // 4. Actualizar la Base de Datos 
            actualizarSaldoBD db = new actualizarSaldoBD();
            db.actualizarSaldo(pantalla.usuarioIdentificado, pantalla.saldoApp);

            // 5. Mostrar el mensaje
            JOptionPane.showMessageDialog(this, "¡Gracias! ¡Tus " + montoDonado + " Auras han sido donadas!");
            
            // 6. Limpiar el campo y actualizar el label del saldo visualmente
            jTextField8.setText("");
            jLabel14.setText(String.valueOf(pantalla.saldoApp)); 
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Introduce un número válido para donar.");
    }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

void limpiar(){
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
}

}


